from backend.database import get_db


def seed_data():
    with get_db() as conn:
        for article in ('der', 'die', 'das'):
            conn.execute("INSERT OR IGNORE INTO articles (name) VALUES (?)", (article,))

        for wt in ('Noun', 'Verb', 'Adjective', 'Adverb'):
            conn.execute("INSERT OR IGNORE INTO word_types (name) VALUES (?)", (wt,))

        for cat in (
            'Temel Kelimeler', 'Hayvanlar', 'Aile',
            'Yiyecek & İçecek', 'Renkler', 'Zaman', 'Eylemler', 'Sıfatlar'
        ):
            conn.execute("INSERT OR IGNORE INTO word_categories (name) VALUES (?)", (cat,))

        # article_id : 1=der  2=die  3=das  None=fiil/sıfat/zarf
        # type_id    : 1=Noun 2=Verb 3=Adjective 4=Adverb
        # category_id: 1=Temel 2=Hayvanlar 3=Aile 4=Yiyecek 5=Renkler 6=Zaman 7=Eylemler 8=Sıfatlar

        # (german_word, turkish_meaning, example_sentence_de, example_sentence_tr,
        #  article_id, category_id, type_id, level)

        a1_words = [
            ('Mann',      'adam',      'Der Mann ist groß.',          'Adam büyük.',          1, 1, 1, 'A1'),
            ('Frau',      'kadın',     'Die Frau liest ein Buch.',    'Kadın kitap okuyor.',  2, 1, 1, 'A1'),
            ('Kind',      'çocuk',     'Das Kind spielt.',            'Çocuk oynuyor.',       3, 1, 1, 'A1'),
            ('Haus',      'ev',        'Das Haus ist groß.',          'Ev büyük.',            3, 1, 1, 'A1'),
            ('Schule',    'okul',      'Die Schule ist neu.',         'Okul yeni.',           2, 1, 1, 'A1'),
            ('Buch',      'kitap',     'Das Buch ist interessant.',   'Kitap ilginç.',        3, 1, 1, 'A1'),
            ('Auto',      'araba',     'Das Auto ist rot.',           'Araba kırmızı.',       3, 1, 1, 'A1'),
            ('Stadt',     'şehir',     'Die Stadt ist groß.',         'Şehir büyük.',         2, 1, 1, 'A1'),
            ('Tisch',     'masa',      'Der Tisch ist braun.',        'Masa kahverengi.',     1, 1, 1, 'A1'),
            ('Stuhl',     'sandalye',  'Der Stuhl ist klein.',        'Sandalye küçük.',      1, 1, 1, 'A1'),
            ('Fenster',   'pencere',   'Das Fenster ist offen.',      'Pencere açık.',        3, 1, 1, 'A1'),
            ('Tür',       'kapı',      'Die Tür ist geschlossen.',    'Kapı kapalı.',         2, 1, 1, 'A1'),
            ('Straße',    'sokak',     'Die Straße ist lang.',        'Sokak uzun.',          2, 1, 1, 'A1'),
            ('Baum',      'ağaç',      'Der Baum ist groß.',          'Ağaç büyük.',          1, 1, 1, 'A1'),
            ('Blume',     'çiçek',     'Die Blume ist schön.',        'Çiçek güzel.',         2, 1, 1, 'A1'),
            ('Geld',      'para',      'Das Geld ist wichtig.',       'Para önemli.',         3, 1, 1, 'A1'),
            ('Name',      'isim',      'Mein Name ist Anna.',         'Benim adım Anna.',     1, 1, 1, 'A1'),
            ('Lehrer',    'öğretmen',  'Der Lehrer erklärt.',         'Öğretmen açıklıyor.',  1, 1, 1, 'A1'),
            ('Küche',     'mutfak',    'Die Küche ist sauber.',       'Mutfak temiz.',        2, 1, 1, 'A1'),
            ('Zimmer',    'oda',       'Das Zimmer ist groß.',        'Oda büyük.',           3, 1, 1, 'A1'),
            ('Hund',      'köpek',     'Der Hund ist groß.',          'Köpek büyük.',         1, 2, 1, 'A1'),
            ('Katze',     'kedi',      'Die Katze schläft.',          'Kedi uyuyor.',         2, 2, 1, 'A1'),
            ('Vogel',     'kuş',       'Der Vogel singt.',            'Kuş şarkı söylüyor.',  1, 2, 1, 'A1'),
            ('Fisch',     'balık',     'Der Fisch schwimmt.',         'Balık yüzüyor.',       1, 2, 1, 'A1'),
            ('Pferd',     'at',        'Das Pferd ist schnell.',      'At hızlı.',            3, 2, 1, 'A1'),
            ('Kuh',       'inek',      'Die Kuh gibt Milch.',         'İnek süt veriyor.',    2, 2, 1, 'A1'),
            ('Mutter',    'anne',      'Meine Mutter kocht.',         'Annem yemek yapıyor.', 2, 3, 1, 'A1'),
            ('Vater',     'baba',      'Mein Vater arbeitet.',        'Babam çalışıyor.',     1, 3, 1, 'A1'),
            ('Bruder',    'erkek kardeş', 'Mein Bruder ist jung.',    'Erkek kardeşim genç.', 1, 3, 1, 'A1'),
            ('Schwester', 'kız kardeş','Meine Schwester liest.',      'Kız kardeşim okuyor.', 2, 3, 1, 'A1'),
            ('Freund',    'erkek arkadaş', 'Mein Freund ist nett.',   'Erkek arkadaşım nazik.',1,3, 1, 'A1'),
            ('Freundin',  'kız arkadaş', 'Meine Freundin lacht.',    'Kız arkadaşım gülüyor.',2,3, 1, 'A1'),
            ('Großvater', 'büyükbaba', 'Mein Großvater ist alt.',    'Büyükbabam yaşlı.',    1, 3, 1, 'A1'),
            ('Großmutter','büyükanne', 'Meine Großmutter kocht.',    'Büyükannem pişiriyor.', 2, 3, 1, 'A1'),
            ('Onkel',     'amca/dayı', 'Mein Onkel wohnt hier.',     'Amcam burada yaşıyor.',1, 3, 1, 'A1'),
            ('Tante',     'hala/teyze','Meine Tante ist nett.',      'Halama nazik.',         2, 3, 1, 'A1'),
            ('Baby',      'bebek',     'Das Baby schläft.',           'Bebek uyuyor.',        3, 3, 1, 'A1'),
            ('Wasser',    'su',        'Das Wasser ist kalt.',        'Su soğuk.',            3, 4, 1, 'A1'),
            ('Brot',      'ekmek',     'Das Brot ist frisch.',        'Ekmek taze.',          3, 4, 1, 'A1'),
            ('Milch',     'süt',       'Die Milch ist warm.',         'Süt ılık.',            2, 4, 1, 'A1'),
            ('Apfel',     'elma',      'Der Apfel ist rot.',          'Elma kırmızı.',        1, 4, 1, 'A1'),
            ('Käse',      'peynir',    'Der Käse ist lecker.',        'Peynir lezzetli.',     1, 4, 1, 'A1'),
            ('Ei',        'yumurta',   'Das Ei ist frisch.',          'Yumurta taze.',        3, 4, 1, 'A1'),
            ('Fleisch',   'et',        'Das Fleisch ist gut.',        'Et iyi.',              3, 4, 1, 'A1'),
            ('Gemüse',    'sebze',     'Das Gemüse ist gesund.',      'Sebze sağlıklı.',      3, 4, 1, 'A1'),
            ('Obst',      'meyve',     'Das Obst ist süß.',           'Meyve tatlı.',         3, 4, 1, 'A1'),
            ('Kaffee',    'kahve',     'Der Kaffee ist heiß.',        'Kahve sıcak.',         1, 4, 1, 'A1'),
            ('Tee',       'çay',       'Der Tee ist warm.',           'Çay ılık.',            1, 4, 1, 'A1'),
            ('Saft',      'meyve suyu','Der Saft ist kalt.',          'Meyve suyu soğuk.',    1, 4, 1, 'A1'),
            ('Tag',       'gün',       'Der Tag ist lang.',           'Gün uzun.',            1, 6, 1, 'A1'),
            ('Nacht',     'gece',      'Die Nacht ist dunkel.',       'Gece karanlık.',       2, 6, 1, 'A1'),
            ('Jahr',      'yıl',       'Das Jahr ist neu.',           'Yıl yeni.',            3, 6, 1, 'A1'),
            ('Monat',     'ay',        'Der Monat ist kurz.',         'Ay kısa.',             1, 6, 1, 'A1'),
            ('Woche',     'hafta',     'Die Woche ist lang.',         'Hafta uzun.',          2, 6, 1, 'A1'),
            ('Stunde',    'saat',      'Die Stunde vergeht schnell.', 'Saat çabuk geçiyor.',  2, 6, 1, 'A1'),
            ('Minute',    'dakika',    'Eine Minute ist kurz.',       'Bir dakika kısa.',     2, 6, 1, 'A1'),
            ('Morgen',    'sabah',     'Der Morgen ist schön.',       'Sabah güzel.',         1, 6, 1, 'A1'),
            ('Abend',     'akşam',     'Der Abend ist ruhig.',        'Akşam sakin.',         1, 6, 1, 'A1'),
            ('sein',      'olmak',     'Ich bin müde.',               'Ben yorgunum.',        None, 7, 2, 'A1'),
            ('haben',     'sahip olmak','Ich habe ein Buch.',         'Benim bir kitabım var.',None,7, 2, 'A1'),
            ('gehen',     'gitmek',    'Ich gehe zur Schule.',        'Okula gidiyorum.',     None, 7, 2, 'A1'),
            ('kommen',    'gelmek',    'Er kommt heute.',             'O bugün geliyor.',     None, 7, 2, 'A1'),
            ('machen',    'yapmak',    'Ich mache meine Hausaufgaben.','Ödevlerimi yapıyorum.',None,7,2, 'A1'),
            ('sagen',     'söylemek',  'Sie sagt die Wahrheit.',      'O gerçeği söylüyor.',  None, 7, 2, 'A1'),
            ('sehen',     'görmek',    'Ich sehe den Vogel.',         'Kuşu görüyorum.',      None, 7, 2, 'A1'),
            ('essen',     'yemek yemek','Ich esse Brot.',             'Ekmek yiyorum.',       None, 7, 2, 'A1'),
            ('trinken',   'içmek',     'Er trinkt Wasser.',           'O su içiyor.',         None, 7, 2, 'A1'),
            ('schlafen',  'uyumak',    'Das Kind schläft.',           'Çocuk uyuyor.',        None, 7, 2, 'A1'),
            ('lesen',     'okumak',    'Sie liest ein Buch.',         'O kitap okuyor.',      None, 7, 2, 'A1'),
            ('schreiben', 'yazmak',    'Ich schreibe einen Brief.',   'Mektup yazıyorum.',    None, 7, 2, 'A1'),
            ('sprechen',  'konuşmak',  'Er spricht Deutsch.',         'O Almanca konuşuyor.', None, 7, 2, 'A1'),
            ('hören',     'duymak',    'Ich höre Musik.',             'Müzik duyuyorum.',     None, 7, 2, 'A1'),
            ('kaufen',    'satın almak','Sie kauft Brot.',            'O ekmek alıyor.',      None, 7, 2, 'A1'),
            ('wohnen',    'yaşamak',   'Ich wohne in Berlin.',        'Berlin\'de yaşıyorum.',None, 7, 2, 'A1'),
            ('lernen',    'öğrenmek',  'Ich lerne Deutsch.',          'Almanca öğreniyorum.', None, 7, 2, 'A1'),
            ('arbeiten',  'çalışmak',  'Er arbeitet viel.',           'O çok çalışıyor.',     None, 7, 2, 'A1'),
            ('spielen',   'oynamak',   'Das Kind spielt.',            'Çocuk oynuyor.',       None, 7, 2, 'A1'),
            ('fahren',    'sürmek',    'Ich fahre Auto.',             'Araba sürüyorum.',     None, 7, 2, 'A1'),
            ('groß',      'büyük',     'Das Haus ist groß.',          'Ev büyük.',            None, 8, 3, 'A1'),
            ('klein',     'küçük',     'Die Katze ist klein.',        'Kedi küçük.',          None, 8, 3, 'A1'),
            ('gut',       'iyi',       'Das Essen ist gut.',          'Yemek iyi.',           None, 8, 3, 'A1'),
            ('schlecht',  'kötü',      'Das Wetter ist schlecht.',    'Hava kötü.',           None, 8, 3, 'A1'),
            ('neu',       'yeni',      'Das Auto ist neu.',           'Araba yeni.',          None, 8, 3, 'A1'),
            ('alt',       'eski/yaşlı','Der Mann ist alt.',           'Adam yaşlı.',          None, 8, 3, 'A1'),
            ('schön',     'güzel',     'Die Blume ist schön.',        'Çiçek güzel.',         None, 8, 3, 'A1'),
            ('schnell',   'hızlı',     'Der Zug ist schnell.',        'Tren hızlı.',          None, 8, 3, 'A1'),
            ('kalt',      'soğuk',     'Das Wasser ist kalt.',        'Su soğuk.',            None, 8, 3, 'A1'),
            ('warm',      'sıcak/ılık','Der Tee ist warm.',           'Çay ılık.',            None, 8, 3, 'A1'),
            ('jung',      'genç',      'Das Mädchen ist jung.',       'Kız genç.',            None, 8, 3, 'A1'),
            ('richtig',   'doğru',     'Das ist richtig.',            'Bu doğru.',            None, 8, 3, 'A1'),
            ('falsch',    'yanlış',    'Das ist falsch.',             'Bu yanlış.',           None, 8, 3, 'A1'),
            ('rot',       'kırmızı',   'Das Auto ist rot.',           'Araba kırmızı.',       None, 5, 3, 'A1'),
            ('blau',      'mavi',      'Der Himmel ist blau.',        'Gökyüzü mavi.',        None, 5, 3, 'A1'),
            ('grün',      'yeşil',     'Das Gras ist grün.',          'Çim yeşil.',           None, 5, 3, 'A1'),
            ('gelb',      'sarı',      'Die Sonne ist gelb.',         'Güneş sarı.',          None, 5, 3, 'A1'),
            ('schwarz',   'siyah',     'Die Nacht ist schwarz.',      'Gece siyah.',          None, 5, 3, 'A1'),
            ('weiß',      'beyaz',     'Der Schnee ist weiß.',        'Kar beyaz.',           None, 5, 3, 'A1'),
            ('langsam',   'yavaş',     'Das Auto ist langsam.',       'Araba yavaş.',         None, 8, 3, 'A1'),
            ('lecker',    'lezzetli',  'Das Essen ist lecker.',       'Yemek lezzetli.',      None, 8, 3, 'A1'),
            ('offen',     'açık',      'Die Tür ist offen.',          'Kapı açık.',           None, 8, 3, 'A1'),
        ]

        a2_words = [
            ('Krankenhaus', 'hastane',   'Das Krankenhaus ist groß.',     'Hastane büyük.',           3, 1, 1, 'A2'),
            ('Bahnhof',     'tren garı', 'Der Bahnhof ist alt.',          'Tren garı eski.',          1, 1, 1, 'A2'),
            ('Flughafen',   'havalimanı','Der Flughafen ist modern.',     'Havalimanı modern.',       1, 1, 1, 'A2'),
            ('Supermarkt',  'süpermarket','Der Supermarkt ist groß.',     'Süpermarket büyük.',       1, 1, 1, 'A2'),
            ('Rathaus',     'belediye',  'Das Rathaus ist im Zentrum.',   'Belediye merkezdedir.',    3, 1, 1, 'A2'),
            ('Bibliothek',  'kütüphane', 'Die Bibliothek ist ruhig.',     'Kütüphane sessiz.',        2, 1, 1, 'A2'),
            ('Museum',      'müze',      'Das Museum ist interessant.',   'Müze ilginç.',             3, 1, 1, 'A2'),
            ('Restaurant',  'restoran',  'Das Restaurant ist voll.',      'Restoran dolu.',           3, 1, 1, 'A2'),
            ('Hotel',       'otel',      'Das Hotel ist teuer.',          'Otel pahalı.',             3, 1, 1, 'A2'),
            ('Büro',        'ofis',      'Das Büro ist modern.',          'Ofis modern.',             3, 1, 1, 'A2'),
            ('Zeitung',     'gazete',    'Die Zeitung ist aktuell.',      'Gazete güncel.',           2, 1, 1, 'A2'),
            ('Computer',    'bilgisayar','Der Computer ist neu.',         'Bilgisayar yeni.',         1, 1, 1, 'A2'),
            ('Handy',       'cep telefonu','Das Handy ist modern.',       'Cep telefonu modern.',     3, 1, 1, 'A2'),
            ('Internet',    'internet',  'Das Internet ist schnell.',     'İnternet hızlı.',          3, 1, 1, 'A2'),
            ('Telefon',     'telefon',   'Das Telefon klingelt.',         'Telefon çalıyor.',         3, 1, 1, 'A2'),
            ('Adresse',     'adres',     'Die Adresse ist richtig.',      'Adres doğru.',             2, 1, 1, 'A2'),
            ('Problem',     'problem',   'Das Problem ist groß.',         'Problem büyük.',           3, 1, 1, 'A2'),
            ('Antwort',     'cevap',     'Die Antwort ist klar.',         'Cevap açık.',              2, 1, 1, 'A2'),
            ('Frage',       'soru',      'Die Frage ist schwierig.',      'Soru zor.',                2, 1, 1, 'A2'),
            ('Idee',        'fikir',     'Die Idee ist gut.',             'Fikir iyi.',               2, 1, 1, 'A2'),
            ('Meinung',     'görüş',     'Meine Meinung ist klar.',       'Benim görüşüm açık.',      2, 1, 1, 'A2'),
            ('Erfahrung',   'deneyim',   'Die Erfahrung ist wichtig.',    'Deneyim önemli.',          2, 1, 1, 'A2'),
            ('Sprache',     'dil',       'Die Sprache ist schön.',        'Dil güzel.',               2, 1, 1, 'A2'),
            ('Wort',        'kelime',    'Das Wort ist neu.',             'Kelime yeni.',             3, 1, 1, 'A2'),
            ('Elefant',     'fil',       'Der Elefant ist groß.',         'Fil büyük.',               1, 2, 1, 'A2'),
            ('Papagei', 'papağan', 'Der Papagei spricht.',                'Papağan konuşuyor.',       1, 2, 1, 'A2'),
            ('Löwe',        'aslan',     'Der Löwe ist stark.',           'Aslan güçlü.',             1, 2, 1, 'A2'),
            ('Tiger',       'kaplan',    'Der Tiger ist gefährlich.',     'Kaplan tehlikeli.',        1, 2, 1, 'A2'),
            ('Affe',        'maymun',    'Der Affe ist lustig.',          'Maymun komik.',            1, 2, 1, 'A2'),
            ('Schlange',    'yılan',     'Die Schlange ist lang.',        'Yılan uzun.',              2, 2, 1, 'A2'),
            ('Maus',        'fare',      'Die Maus ist klein.',           'Fare küçük.',              2, 2, 1, 'A2'),
            ('Kaninchen',   'tavşan',    'Das Kaninchen ist süß.',        'Tavşan şirin.',            3, 2, 1, 'A2'),
            ('Ente',        'ördek',     'Die Ente schwimmt.',            'Ördek yüzüyor.',           2, 2, 1, 'A2'),
            ('Schaf',       'koyun',     'Das Schaf ist weiß.',           'Koyun beyaz.',             3, 2, 1, 'A2'),
            ('Ehemann',     'koca',      'Mein Ehemann arbeitet.',        'Kocam çalışıyor.',         1, 3, 1, 'A2'),
            ('Ehefrau',     'eş (kadın)','Meine Ehefrau kocht.',          'Eşim yemek yapıyor.',      2, 3, 1, 'A2'),
            ('Sohn',        'oğul',      'Mein Sohn ist jung.',           'Oğlum genç.',              1, 3, 1, 'A2'),
            ('Tochter',     'kız çocuğu','Meine Tochter lernt.',          'Kızım öğreniyor.',         2, 3, 1, 'A2'),
            ('Cousin',      'erkek kuzen','Mein Cousin wohnt weit.',      'Erkek kuzenim uzakta yaşıyor.',1,3,1,'A2'),
            ('Cousine',     'kız kuzen', 'Meine Cousine ist nett.',       'Kız kuzenim nazik.',       2, 3, 1, 'A2'),
            ('Neffe',       'yeğen (erkek)','Mein Neffe spielt.',         'Erkek yeğenim oynuyor.',   1, 3, 1, 'A2'),
            ('Nichte',      'yeğen (kız)','Meine Nichte lacht.',          'Kız yeğenim gülüyor.',     2, 3, 1, 'A2'),
            ('Familie',     'aile',      'Meine Familie ist groß.',       'Ailem büyük.',             2, 3, 1, 'A2'),
            ('Suppe',       'çorba',     'Die Suppe ist heiß.',           'Çorba sıcak.',             2, 4, 1, 'A2'),
            ('Kuchen',      'pasta/kek', 'Der Kuchen ist süß.',           'Pasta tatlı.',             1, 4, 1, 'A2'),
            ('Schokolade',  'çikolata',  'Die Schokolade ist lecker.',    'Çikolata lezzetli.',       2, 4, 1, 'A2'),
            ('Reis',        'pirinç/pilav','Der Reis ist fertig.',        'Pilav hazır.',             1, 4, 1, 'A2'),
            ('Salat',       'salata',    'Der Salat ist frisch.',         'Salata taze.',             1, 4, 1, 'A2'),
            ('Zucker',      'şeker',     'Der Zucker ist süß.',           'Şeker tatlı.',             1, 4, 1, 'A2'),
            ('Salz',        'tuz',       'Das Salz ist wichtig.',         'Tuz önemli.',              3, 4, 1, 'A2'),
            ('Butter',      'tereyağı',  'Die Butter ist frisch.',        'Tereyağı taze.',           2, 4, 1, 'A2'),
            ('Wein',        'şarap',     'Der Wein ist gut.',             'Şarap iyi.',               1, 4, 1, 'A2'),
            ('Nudeln',      'makarna',   'Die Nudeln sind lecker.',       'Makarna lezzetli.',        2, 4, 1, 'A2'),
            ('orange',      'turuncu',   'Das T-Shirt ist orange.',       'Tişört turuncu.',          None, 5, 3, 'A2'),
            ('lila',        'mor',       'Die Blume ist lila.',           'Çiçek mor.',               None, 5, 3, 'A2'),
            ('rosa',        'pembe',     'Das Kleid ist rosa.',           'Elbise pembe.',            None, 5, 3, 'A2'),
            ('braun',       'kahverengi','Der Tisch ist braun.',          'Masa kahverengi.',         None, 5, 3, 'A2'),
            ('grau',        'gri',       'Die Wolke ist grau.',           'Bulut gri.',               None, 5, 3, 'A2'),
            ('Frühling',    'ilkbahar',  'Der Frühling ist warm.',        'İlkbahar sıcak.',          1, 6, 1, 'A2'),
            ('Sommer',      'yaz',       'Der Sommer ist heiß.',          'Yaz sıcak.',               1, 6, 1, 'A2'),
            ('Herbst',      'sonbahar',  'Der Herbst ist kühl.',          'Sonbahar serin.',          1, 6, 1, 'A2'),
            ('Winter',      'kış',       'Der Winter ist kalt.',          'Kış soğuk.',               1, 6, 1, 'A2'),
            ('Wochenende',  'hafta sonu','Das Wochenende ist schön.',     'Hafta sonu güzel.',        3, 6, 1, 'A2'),
            ('Feiertag',    'tatil günü','Der Feiertag ist morgen.',      'Tatil günü yarın.',        1, 6, 1, 'A2'),
            ('Urlaub',      'tatil',     'Der Urlaub ist lang.',          'Tatil uzun.',              1, 6, 1, 'A2'),
            ('Uhr',         'saat',       'Die Uhr ist kaputt.',           'Saat bozuk.',              2, 6, 1, 'A2'),
            ('verstehen',   'anlamak',   'Ich verstehe das nicht.',       'Bunu anlamıyorum.',        None, 7, 2, 'A2'),
            ('erklären',    'açıklamak', 'Er erklärt die Aufgabe.',       'O görevi açıklıyor.',      None, 7, 2, 'A2'),
            ('helfen',      'yardım etmek','Sie hilft mir.',              'O bana yardım ediyor.',    None, 7, 2, 'A2'),
            ('brauchen',    'ihtiyaç duymak','Ich brauche Hilfe.',        'Yardıma ihtiyacım var.',   None, 7, 2, 'A2'),
            ('können',      'yapabilmek','Ich kann schwimmen.',           'Yüzebiliyorum.',           None, 7, 2, 'A2'),
            ('müssen',      'zorunda olmak','Du musst lernen.',           'Öğrenmek zorundasın.',     None, 7, 2, 'A2'),
            ('wollen',      'istemek',   'Ich will schlafen.',            'Uyumak istiyorum.',        None, 7, 2, 'A2'),
            ('dürfen',      'izni olmak','Du darfst hier sitzen.',        'Burada oturabilirsin.',    None, 7, 2, 'A2'),
            ('sollen',      'yapması gerekmek','Du sollst arbeiten.',     'Çalışman gerekiyor.',      None, 7, 2, 'A2'),
            ('mögen',       'sevmek',    'Ich mag Musik.',                'Müziği seviyorum.',        None, 7, 2, 'A2'),
            ('vergessen',   'unutmak',   'Ich vergesse oft.',             'Sık sık unutuyorum.',      None, 7, 2, 'A2'),
            ('erinnern',    'hatırlamak','Ich erinnere mich.',            'Hatırlıyorum.',            None, 7, 2, 'A2'),
            ('besuchen',    'ziyaret etmek','Ich besuche meine Oma.',     'Büyükannemizi ziyaret ediyorum.',None,7,2,'A2'),
            ('reisen',      'seyahat etmek','Sie reist gern.',            'O seyahat etmeyi sever.',  None, 7, 2, 'A2'),
            ('anrufen',     'telefon etmek','Ich rufe dich an.',          'Seni arıyorum.',           None, 7, 2, 'A2'),
            ('interessant', 'ilginç',    'Das Buch ist interessant.',     'Kitap ilginç.',            None, 8, 3, 'A2'),
            ('langweilig',  'sıkıcı',    'Der Film ist langweilig.',      'Film sıkıcı.',             None, 8, 3, 'A2'),
            ('schwierig',   'zor',       'Die Aufgabe ist schwierig.',    'Görev zor.',               None, 8, 3, 'A2'),
            ('einfach',     'kolay/basit','Die Frage ist einfach.',       'Soru kolay.',              None, 8, 3, 'A2'),
            ('laut',        'gürültülü', 'Die Musik ist laut.',           'Müzik gürültülü.',         None, 8, 3, 'A2'),
            ('leise',       'sessiz',    'Das Baby ist leise.',           'Bebek sessiz.',            None, 8, 3, 'A2'),
            ('teuer',       'pahalı',    'Das Auto ist teuer.',           'Araba pahalı.',            None, 8, 3, 'A2'),
            ('billig',      'ucuz',      'Das Brot ist billig.',          'Ekmek ucuz.',              None, 8, 3, 'A2'),
            ('müde',        'yorgun',    'Ich bin müde.',                 'Ben yorgunum.',            None, 8, 3, 'A2'),
            ('gesund',      'sağlıklı',  'Das Essen ist gesund.',         'Yemek sağlıklı.',          None, 8, 3, 'A2'),
            ('krank',       'hasta',     'Er ist krank.',                 'O hasta.',                 None, 8, 3, 'A2'),
            ('froh',        'mutlu',     'Ich bin froh.',                 'Ben mutluyum.',            None, 8, 3, 'A2'),
            ('traurig',     'üzgün',     'Sie ist traurig.',              'O üzgün.',                 None, 8, 3, 'A2'),
            ('glücklich',   'mutlu/şanslı','Ich bin glücklich.',          'Mutluyum.',                None, 8, 3, 'A2'),
            ('stark',       'güçlü',     'Der Mann ist stark.',           'Adam güçlü.',              None, 8, 3, 'A2'),
            ('nett',        'nazik/sevimli','Er ist sehr nett.',           'O çok nazik.',             None, 8, 3, 'A2'),
            ('klug',        'zeki',      'Das Mädchen ist klug.',         'Kız zeki.',                None, 8, 3, 'A2'),
            ('fleißig',     'çalışkan',  'Der Schüler ist fleißig.',      'Öğrenci çalışkan.',        None, 8, 3, 'A2'),
            ('höflich',     'kibar',     'Sie ist höflich.',              'O kibar.',                 None, 8, 3, 'A2'),
            ('gefährlich',  'tehlikeli', 'Das ist gefährlich.',           'Bu tehlikeli.',            None, 8, 3, 'A2'),
        ]

        # NOT: örnek cümleler şimdilik statik placeholder.
        # Final aşamasında T5 modeli ile otomatik üretilip güncellenecek.
        conn.executemany(
            '''INSERT OR IGNORE INTO words
               (german_word, turkish_meaning, example_sentence_de, example_sentence_tr,
                article_id, category_id, type_id, level)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)''',
            a1_words + a2_words
        )

    print(f"Veriler başarıyla eklendi. ({len(a1_words)} A1 + {len(a2_words)} A2 = {len(a1_words)+len(a2_words)} kelime)")


if __name__ == '__main__':
    seed_data()